language: generic
os: linux

install:
- cd ci/
- source texlive.sh
- cd ..

cache:
  directories:
  - /tmp/texlive
  - $HOME/.texlive
  - /tmp/tlpkg

addons:
  apt:
    packages:
    - ghostscript
    - libxml-parser-perl
    - libxml-xpath-perl
    - libtext-unidecode-perl
    - realpath

before_script:
- git fetch --unshallow --tags
- texlua build.lua revisionfile
- cat tex/generic/pgf/pgf.revision.tex

script:
- texlua build.lua manual ${version}

jobs:
  include:
  - env: version=luatex
    after_success:
    - texlua build.lua ctan
    - cp doc/generic/pgf/version-for-luatex/en/pgfmanual.pdf ../
    - bash ci/update_tlcontrib.sh

  - env: version=dvisvgm
    after_success:
    - cd doc/generic/pgf/version-for-dvisvgm/en
    - bash ../../../../../ci/update_website.sh

  - env: version=dvipdfm

  - env: version=dvipdfmx

  - env: version=dvips

  - env: version=pdftex

  - env: version=tex4ht

  - env: version=xetex

deploy:
  provider: releases
  token: $GH_TOKEN
  file_glob: true
  file:
  - pgf_*.zip
  - doc/generic/pgf/version-for-luatex/en/pgfmanual.pdf
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    condition: $version = luatex
