language: generic

install:
- cd ci/
- source texlive.sh
- cd ..

cache:
  directories:
  - /tmp/texlive
  - $HOME/.texlive
  - /tmp/tlpkg

addons:
  apt:
    packages:
    - ghostscript
    - libxml-parser-perl
    - libxml-xpath-perl
    - libtext-unidecode-perl
    - realpath

before_script:
- git fetch --unshallow --tags
- bash scripts/pgf/pgfrevisionfile.sh
- cat tex/generic/pgf/pgf.revision.tex

matrix:
  include:
  - env: version=dvipdfm
    script:
    - cd doc/generic/pgf/version-for-dvipdfm/en
    - make latex="latex --interaction=nonstopmode"

  - env: version=dvidfmx
    script:
    - cd doc/generic/pgf/version-for-dvipdfmx/en
    - make latex="latex -shell-escape --interaction=nonstopmode"

  - env: version=dvips
    script:
    - cd doc/generic/pgf/version-for-dvips/en
    - make latex="latex --interaction=nonstopmode"

  - env: version=dvisvgm
    script:
    - cd doc/generic/pgf/version-for-dvisvgm/en
    - touch pgfmanual.toc
    - make latex="lualatex --output-format=dvi --interaction=nonstopmode"
    - bash ../../../../../ci/update_website.sh

  - env: version=luatex
    script:
    - cd doc/generic/pgf/version-for-luatex/en
    - make latex="lualatex --interaction=nonstopmode"
    - cp pgfmanual.pdf ../../
    - cd ../../../../../
    - bash ci/update_tlcontrib.sh

  - env: version=pdftex
    script:
    - cd doc/generic/pgf/version-for-pdftex/en
    - make latex="pdflatex --interaction=nonstopmode"

#  - env: version=tex4ht
#    script:
#    - cd doc/generic/pgf/version-for-tex4ht/en
#    - make

#  - env: version=vtex
#    script:
#    - cd doc/generic/pgf/version-for-vtex/en
#    - make

  - env: version=xetex
    script:
    - cd doc/generic/pgf/version-for-xetex/en
    - make latex="xelatex --no-pdf --interaction=nonstopmode"

  - if: repo = pgf-tikz/pgf AND type != pull_request
    env: update=sourceforge
    before_install:
    - openssl aes-256-cbc -K $encrypted_fd6ed174e9a3_key -iv $encrypted_fd6ed174e9a3_iv
      -in ci/deploy_key.enc -out ci/deploy_key -d
    install:
    - git clone --mirror https://github.com/pgf-tikz/pgf.git pgf-git-mirror
    - cd pgf-git-mirror
    before_script:
    - eval "$(ssh-agent -s)"
    - chmod 600 ../ci/deploy_key
    - echo -e "Host git.code.sf.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - ssh-add ../ci/deploy_key
    script:
    - git remote add sf ssh://hmenke@git.code.sf.net/p/pgf/git
    - git push --mirror --force sf
